### ISSUE TITLE
Horizon Zero Dawn: DLSS breaks image after opening journal/inventory/map 

### ISSUE THREAD

**Issue by FantixX** [HansKristian-Work/vkd3d-proton#1194]
- image returns to normal after disabling DLSS
- happens with latest Proton Stable/Experimental/GE 
- Using PROTON_HIDE_NVIDIA_GPU=0 PROTON_ENABLE_NVAPI=1 %command% in Steam startup flags
![image](https://user-images.githubusercontent.com/36110782/185480066-ba01cf1e-1833-4a81-81f0-43b49cc386ce.png)

**Comment by Blisto91** [comment]
@FantixX A friendly ping pong hello 👋. Do you still experience this issue?

**Comment by FantixX** [comment]
> @FantixX A friendly ping pong hello 👋. Do you still experience this issue?

cant test it right now, but somebody replied to my reddit post recently, who still experienced this

**Comment by Blisto91** [comment]
Thank you for replying :+1:

**Comment by K0bin** [comment]
I can reproduce the problem. On top of that, I got a GPU hang when changing the settings from low to ultra.

`[14813.035031] NVRM: Xid (PCI:0000:08:00): 31, pid=26266, name=HorizonZeroDawn, Ch 0000015e, intr 00000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_GCC faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ`

**Comment by CME42** [comment]
seems like it crashes with that bt:
```
(gdb) bt
#0  0x000000007d001499 in sync_wine_link_map ()
#1  0x000000007d0018a7 in dlopen ()
#2  0x00007f28471d82b5 in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so
#3  0x00007f28471d710c in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so
#4  0x00007f2845d2458b in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so
#5  0x00007f2845c57fb0 in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so
#6  0x00007f284586c34a in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so
#7  0x00007f2848efcabe in call_init (env=0x7ffdd45a1788, argv=0x7ffdd45a1768, argc=3, l=<optimized out>) at ./elf/dl-init.c:70
#8  call_init (l=<optimized out>, argc=3, argv=0x7ffdd45a1768, env=0x7ffdd45a1788) at ./elf/dl-init.c:26
#9  0x00007f2848efcba4 in _dl_init (main_map=0x7e0a3250, argc=3, argv=0x7ffdd45a1768, env=0x7ffdd45a1788) at ./elf/dl-init.c:117
#10 0x00007f2848e01ef4 in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7f2848f03370 <call_dl_init>, args=args@entry=0x7ffdd45a03e0) at ./elf/dl-error-skeleton.c:182
#11 0x00007f2848f0330e in dl_open_worker (a=a@entry=0x7ffdd45a0580) at ./elf/dl-open.c:808
#12 0x00007f2848e01e9a in __GI__dl_catch_exception (exception=exception@entry=0x7ffdd45a0560, operate=operate@entry=0x7f2848f03280 <dl_open_worker>, args=args@entry=0x7ffdd45a0580) at ./elf/dl-error-skeleton.c:208
#13 0x00007f2848f036a8 in _dl_open (file=0x7e0a1600 "/home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNvda.Graphics.Interception.so", mode=<optimized out>, caller_dlopen=0x7f28484bc151, 
    nsid=<optimized out>, argc=3, argv=0x7ffdd45a1768, env=0x7ffdd45a1788) at ./elf/dl-open.c:884
#14 0x00007f2848d382d8 in dlopen_doit (a=a@entry=0x7ffdd45a07f0) at ./dlfcn/dlopen.c:56
#15 0x00007f2848e01e9a in __GI__dl_catch_exception (exception=exception@entry=0x7ffdd45a0750, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:208
#16 0x00007f2848e01f4f in __GI__dl_catch_error (objname=0x7ffdd45a07a8, errstring=0x7ffdd45a07b0, mallocedp=0x7ffdd45a07a7, operate=<optimized out>, args=<optimized out>) at ./elf/dl-error-skeleton.c:227
#17 0x00007f2848d37dc7 in _dlerror_run (operate=operate@entry=0x7f2848d38280 <dlopen_doit>, args=args@entry=0x7ffdd45a07f0) at ./dlfcn/dlerror.c:138
#18 0x00007f2848d38389 in dlopen_implementation (dl_caller=<optimized out>, mode=<optimized out>, file=<optimized out>) at ./dlfcn/dlopen.c:71
#19 ___dlopen (file=<optimized out>, mode=<optimized out>) at ./dlfcn/dlopen.c:81
#20 0x00007f28484bc151 in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNomad.Injection.so
#21 0x00007f28484c07bb in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNomad.Injection.so
#22 0x00007f28484c3804 in ?? () from /home/cme/nvidia/NVIDIA-Nsight-Graphics-2022.7/target/linux-desktop-nomad-x64/libNomad.Injection.so
#23 <signal handler called>
#24 0x00007f28488c5000 in ?? () from /lib/x86_64-linux-gnu/libmd.so.0
#25 0x00007f2848efca79 in call_init (env=0x7ffdd45a1788, argv=0x7ffdd45a1768, argc=3, l=0x7f28488e6b20) at ./elf/dl-init.c:56
#26 call_init (l=0x7f28488e6b20, argc=3, argv=0x7ffdd45a1768, env=0x7ffdd45a1788) at ./elf/dl-init.c:26
#27 0x00007f2848efcba4 in _dl_init (main_map=0x7f2848f2b2e0, argc=3, argv=0x7ffdd45a1768, env=0x7ffdd45a1788) at ./elf/dl-init.c:117
#28 0x00007f2848f129f0 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#29 0x0000000000000003 in ?? ()
#30 0x00007ffdd45a2014 in ?? ()
#31 0x00007ffdd45a20ad in ?? ()
#32 0x00007ffdd45a20cb in ?? ()
#33 0x0000000000000000 in ?? ()
```
