### ISSUE TITLE
Mario Kart DX12 - Title fails at launch.

### ISSUE THREAD

**Issue by ZereoX** [HansKristian-Work/vkd3d-proton#668]
### Description:
**_Mario Kart DX12_** (1038250) fails at launch with a blank window before closing.

| Windows w/ VKD3D-Proton (2.3.1) |
| ---- |
|![image](https://user-images.githubusercontent.com/761853/119214115-3e691e00-ba92-11eb-9e15-a1ff13d1c132.png)|

Please let me know if any additional information is required or if additional testing is needed.

### Software information
- Mario Kart DX12 can be downloaded of [itch.io](https://mattfiler.itch.io/mario-kart-dx12). 
- Source is available here: https://github.com/MattFiler/ThICC_Engine
- This is a 32-bit DX12 title.

### System information
OS: Windows 10 Pro 1909
GPU: AMD Radeon RX 5700 XT
Drivers: 21.4.1
Wine version: N/A
VKD3D-Proton version: 2.3.1 / Master (925a930)

### Log files
Log (w/ VKD3D_DEBUG=trace): [ThICC_Engine_VKD3D.log](https://github.com/HansKristian-Work/vkd3d-proton/files/6525761/ThICC_Engine_VKD3D.log)

**Comment by Joshua-Ashton** [comment]
This used to work on NVIDIA with VKD3D-Proton. I'll see if it works on RADV and NV still later.

**Comment by Joshua-Ashton** [comment]
Crashes in
```
#0  0x6fa00cfa in d3d12_command_list_Reset@12 ()
#1  0x6f9c4aca in d3d12_device_CreateCommandList@28 ()
```

**Comment by Joshua-Ashton** [comment]
Okay it sometimes works, sometimes doesn't. One time I got a crash in wine_vkQueueSubmit.

Very weird

**Comment by Joshua-Ashton** [comment]
Okay and now I can't get it to crash again, blah.

**Comment by ZereoX** [comment]
This issue still occurs as reported on master (1317cf8).
